kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "home-assistant.fullname" . }}-config
  namespace: home
data:
    configuration.yaml: |
      {{- if .Values.configurationYaml }}
      {{- toYaml .Values.configurationYaml | nindent 8 }}
      {{- else }}
      # Loads default set of integrations. Do not remove.
      default_config:
      # Load frontend themes from the themes folder
      frontend:
        themes: !include_dir_merge_named themes

      automation: !include automations.yaml
      script: !include scripts.yaml
      scene: !include scenes.yaml
      {{- end  }}
