{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
    {{- with .Values.metrics.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
      {{- include "home-assistant.selectorLabels" . | nindent 6 }}
      rules:
        - alert: HomeAssistantAbsent
          annotations:
            description: Home Assistant has disappeared from Prometheus service discovery.
            summary: Home Assistant is down.
          expr: |
            absent(up{job=~".*{{ include "home-assistant.fullname" . }}.*"} == 1)
          for: 5m
          labels:
            severity: critical
        {{- with .Values.metrics.prometheusRule.rules }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}