tolerations:
- key: "location"
  operator: "Equal"
  value: "home"
  effect: "NoExecute"
nodeSelector:
  location: home

persistence:
  enabled: true
  config:
    enabled: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
  - host: home.sprauer.net
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls:
  - secretName: ingress-cert
    hosts:
    - home.sprauer.net

postgresql: # documentation bitnami postgresql: https://github.com/bitnami/charts/tree/main/bitnami/postgresql
  enabled: true
  primary:
    nodeSelector:
      location: home
    tolerations:
    - key: "location"
      operator: "Equal"
      value: "home"
      effect: "NoExecute"
