---
name: "Metadata: Label pull requests"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - closed
      - reopened
      - ready_for_review
      - synchronize

jobs:
  label-size:
    name: Label Size
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Label Size
        uses: pascalgn/size-label-action@v0.5.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          sizes: >
            {
              "0": "XS",
              "20": "S",
              "50": "M",
              "200": "L",
              "800": "XL",
              "2000": "XXL"
            }
