---
name: "Metadata: Label Commenter"

on:
  issues:
    types:
      - labeled
      - unlabeled
  pull_request_target:
    types:
      - labeled
      - unlabeled

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  comment:
    name: Label commenter
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: peaceiris/actions-label-commenter@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
